[package]
name = "gpu-messurement-service"
version = "0.1.0"
edition = "2021"

[dependencies]
nvml-wrapper = "0.10"
serde = "1.0"
tokio = { version = "1.36", features = ["rt", "macros"] }
warp = "0.3"
