openapi: 3.1.0
info:
  title: GPU measurement service
  summary: API for measuring energy consumption of GPUs
  version: 1.0.0
  description: |
    This API allows performing *measurements* within *campaigns*. A new campaing
    is started via a POST to the `/v1/energy` end-point:

        POST /v1/energy

    The end-point will respond with a `303 See Other` status and a `Location`
    header containing the URI of the end-point associated to the new campaign.

        HTTP/1.1 303 See Other
        Location: /v1/energy/0

    Subsequent GET requests on that end-point will yield a new measurement
    relative to the instant the campaign was created.
paths:
  /v1/device_count:
    get:
      summary: Retrieve the number of devices
      description: |
        This request yields with the number of distinct devices (i.e. GPUs)
        addressable through this service. Devices are enumerated, starting from
        `0` up to, not including, this value.
      responses:
        '200':
          description: The number of devices
          content:
            application/json:
              schema:
                type: integer
        default:
          $ref: '#/components/responses/error'
  /v1/device/{id}/name:
    get:
      summary: Retrieve the name of a device
      responses:
        '200':
          description: The name of the device
          content:
            application/json:
              schema:
                type: string
        default:
          $ref: '#/components/responses/error'
      parameters:
      - $ref: '#/components/parameters/device_id'
  /v1/device/{id}/uuid:
    get:
      summary: Retrieve the UUID of a device
      responses:
        '200':
          description: The UUID of the device
          content:
            application/json:
              schema:
                type: string
        default:
          $ref: '#/components/responses/error'
      parameters:
      - $ref: '#/components/parameters/device_id'
  /v1/device/{id}/serial:
    get:
      summary: Retrieve the serial of a device
      responses:
        '200':
          description: The serial of the device
          content:
            application/json:
              schema:
                type: string
        default:
          $ref: '#/components/responses/error'
      parameters:
      - $ref: '#/components/parameters/device_id'
  /v1/device/{id}/power_usage:
    get:
      summary: Retrieve the current power usage of a device
      responses:
        '200':
          description: The current power usage of the device in mW
          content:
            application/json:
              schema:
                type: integer
        default:
          $ref: '#/components/responses/error'
      parameters:
      - $ref: '#/components/parameters/device_id'
  /v1/energy:
    get:
      summary: Perform a oneshot measurement of energy consumption
      responses:
        '200':
          $ref: '#/components/responses/measurement'
        default:
          $ref: '#/components/responses/error'
      parameters:
      - name: duration
        in: query
        description: number of ms to measure
        schema:
          type: integer
    post:
      summary: Create a new measurement campaign
      responses:
        '303':
          description: Redirect to the new campaign
        default:
          $ref: '#/components/responses/error'
  /v1/energy/{campaign}:
    get:
      summary: Get a new measurement for the campaign
      responses:
        '200':
          $ref: '#/components/responses/measurement'
        default:
          $ref: '#/components/responses/error'
      parameters:
      - $ref: '#/components/parameters/campaign_id'
    delete:
      summary: End a specific campaign
      responses:
        '200':
          description: The campaign ended.
        '404':
          description: A campaign with the provided id does not exist
        default:
          $ref: '#/components/responses/error'
      parameters:
      - $ref: '#/components/parameters/campaign_id'
  /v1/ping:
    get:
      summary: Simple ping endpoint
      responses:
        '200':
          description: Empty ping response
  /v1/health:
    get:
      summary: Perform a health-check
      responses:
        '200':
          description: Health data of the service
          content:
            application/json:
              schema:
                type: object
                properties:
                  device_count:
                    type: integer
                  version:
                    type: string
                  driver_version:
                    type: string
                  nvml_version:
                    type: string
                  campaigns:
                    type: integer
                  oneshot_enabled:
                    type: boolean
        default:
          $ref: '#/components/responses/error'
components:
  responses:
    measurement:
      description: The duration in ms and devices' energy consumptions in mJ
      content:
        application/json:
          schema:
            type: object
            properties:
              time:
                type: integer
              devices:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    energy:
                      type: integer
    error:
      description: Unexpected error
  parameters:
    device_id:
      name: id
      in: path
      description: device id
      required: true
      schema:
        type: integer
    campaign_id:
      name: id
      in: path
      description: campaign id
      required: true
      schema:
        type: integer
